name: 'Release'
on:
  push:
    branches:
      - main
      - dev

jobs:
  release-server-sdk-python:
    name: 'Publish new version'
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/release-server-sdk.yml@v1
    with:
      appId: ${{ vars.APP_ID }}
      language: python
      language-version: '3.12'
      semantic-release-extra-plugins: |
        semantic-release-pypi@2.5.0
      prepare-command: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install wheel
        pip install twine
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
