name: release

on:
  push:
    branches:
      - semantic-release
  workflow_dispatch:

jobs:
  publish:
    environment: production
    name: Build and publish
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-semantic-release

      - name: "Build and publish with semantic-release"
        run: "semantic-release publish --prerelease --verbosity=DEBUG"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_USERNAME: ${{ secrets.PYPI_USERNAME }}
          REPOSITORY_PASSWORD: ${{ secrets.PYPI_PASSWORD }}