name: release

on:
  push:
    branches:
      - main
      - dev

jobs:
  publish:
    environment: production
    name: Build and publish
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-semantic-release

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@91ab76a4a393a8d0c4739e9aea1818b56bc953ea
        with:
          extra_plugins: |
            @semantic-release/exec@6.0.3
            conventional-changelog-conventionalcommits@5.0.0
            semantic-release-pypi@2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
